dqn:
  nb_neurons: 512
  depth: 5

training:
  learning_rate: 0.001
  gamma: 0.95
  buffer_size: 50000
  epsilon_min: 0.02
  epsilon_max: 1.0  
  epsilon_decay_period: 25000
  epsilon_delay_decay: 100
  batch_size: 200
  gradient_steps: 5
  update_target_strategy: "replace"
  update_target_freq: 400
  update_target_tau: 0.005
  criterion: "SmoothL1Loss"
